import { formatDateLong } from "./helpers";

/**
 * Generator bahan laporan PKL.
 * Mengubah catatan informal → bahasa formal.
 */
export function generateBahanLaporan(kegiatanList, profil) {
  if (!kegiatanList || kegiatanList.length === 0) {
    return "Tidak ada kegiatan yang dicatat dalam periode ini.";
  }

  const lines = [];

  // Header
  lines.push("LAPORAN KEGIATAN PRAKTIK KERJA LAPANGAN (PKL)");
  lines.push("");
  lines.push(`Nama: ${profil?.nama || "-"}`);
  lines.push(`Kelas: ${profil?.kelas || "-"}`);
  lines.push(`Jurusan: ${profil?.jurusan || "-"}`);
  lines.push(`Sekolah: ${profil?.sekolah || "-"}`);
  lines.push(`Tempat PKL: ${profil?.tempat_pkl || "-"}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Group by tanggal
  const grouped = {};
  kegiatanList.forEach((k) => {
    if (!grouped[k.tanggal]) grouped[k.tanggal] = [];
    grouped[k.tanggal].push(k);
  });

  const sortedDates = Object.keys(grouped).sort();

  sortedDates.forEach((tanggal) => {
    const items = grouped[tanggal];
    lines.push(`Tanggal: ${formatDateLong(tanggal)}`);
    lines.push("");

    items.forEach((k, idx) => {
      // Format kegiatan menjadi kalimat formal
      const kegiatanFormal = formatKegiatanFormal(k.kegiatan);
      lines.push(`${idx + 1}. ${kegiatanFormal}`);

      if (k.software) {
        lines.push(`   Software/Peralatan: ${k.software}`);
      }
      if (k.pembelajaran) {
        lines.push(`   Pembelajaran: ${formatKegiatanFormal(k.pembelajaran)}`);
      }
      if (k.kendala) {
        lines.push(`   Kendala: ${formatKegiatanFormal(k.kendala)}`);
      }
      if (k.solusi) {
        lines.push(`   Solusi: ${formatKegiatanFormal(k.solusi)}`);
      }
      lines.push("");
    });

    lines.push("---");
    lines.push("");
  });

  return lines.join("\n");
}

/**
 * Ubah teks informal menjadi lebih formal.
 * Contoh: "bikin desain" → "membuat desain"
 */
function formatKegiatanFormal(text) {
  if (!text) return "";

  let result = text.trim();

  // Ganti kata informal → formal
  const replacements = [
    { from: /\bbikin\b/gi, to: "membuat" },
    { from: /\bngisi\b/gi, to: "mengisi" },
    { from: /\bngetik\b/gi, to: "mengetik" },
    { from: /\bprint\b/gi, to: "mencetak" },
    { from: /\bdesign\b/gi, to: "desain" },
    { from: /\bedit\b/gi, to: "mengedit" },
    { from: /\bupload\b/gi, to: "mengunggah" },
    { from: /\bdownload\b/gi, to: "mengunduh" },
    { from: /\binput\b/gi, to: "memasukkan" },
    { from: /\bcek\b/gi, to: "memeriksa" },
    { from: /\bsetting\b/gi, to: "mengatur" },
    { from: /\binstall\b/gi, to: "menginstal" },
    { from: /\bhapus\b/gi, to: "menghapus" },
    { from: /\btambah\b/gi, to: "menambahkan" },
    { from: /\bubah\b/gi, to: "mengubah" },
    { from: /\bsimpan\b/gi, to: "menyimpan" },
    { from: /\bbuka\b/gi, to: "membuka" },
    { from: /\btutup\b/gi, to: "menutup" },
    { from: /\bkirim\b/gi, to: "mengirim" },
    { from: /\bterima\b/gi, to: "menerima" },
    { from: /\bbantu\b/gi, to: "membantu" },
    { from: /\bajar\b/gi, to: "belajar" },
    { from: /\bpraktek\b/gi, to: "praktik" },
    { from: /\b praktekin\b/gi, to: " mempraktikkan" },
    { from: /\bcoba\b/gi, to: "mencoba" },
    { from: /\btes\b/gi, to: "menguji" },
    { from: /\btest\b/gi, to: "menguji" },
    { from: /\brevisi\b/gi, to: "melakukan revisi" },
    { from: /\bfix\b/gi, to: "memperbaiki" },
    { from: /\bperbaiki\b/gi, to: "memperbaiki" },
    { from: /\bselesaiin\b/gi, to: "menyelesaikan" },
    { from: /\bselesaikan\b/gi, to: "menyelesaikan" },
    { from: /\blanjutin\b/gi, to: "melanjutkan" },
    { from: /\blanjutkan\b/gi, to: "melanjutkan" },
    { from: /\bmulai\b/gi, to: "memulai" },
    { from: /\bkerjain\b/gi, to: "mengerjakan" },
    { from: /\bkerja\b/gi, to: "bekerja" },
    { from: /\bsiapin\b/gi, to: "mempersiapkan" },
    { from: /\bsiapkan\b/gi, to: "mempersiapkan" },
    { from: /\bbuat\b/gi, to: "membuat" },
    { from: /\bambil\b/gi, to: "mengambil" },
    { from: /\bkasih\b/gi, to: "memberikan" },
    { from: /\bberi\b/gi, to: "memberikan" },
    { from: /\btanya\b/gi, to: "bertanya" },
    { from: /\bjawab\b/gi, to: "menjawab" },
    { from: /\bdiskusi\b/gi, to: "berdiskusi" },
    { from: /\bdiskusiin\b/gi, to: "berdiskusi" },
    { from: /\bpresentasi\b/gi, to: "mempresentasikan" },
    { from: /\bjelasin\b/gi, to: "menjelaskan" },
    { from: /\bjelaskan\b/gi, to: "menjelaskan" },
    { from: /\btunjukin\b/gi, to: "menunjukkan" },
    { from: /\btunjukkan\b/gi, to: "menunjukkan" },
    { from: /\bliat\b/gi, to: "melihat" },
    { from: /\blihat\b/gi, to: "melihat" },
    { from: /\bamat\b/gi, to: "mengamati" },
    { from: /\bobservasi\b/gi, to: "mengamati" },
    { from: /\banalisis\b/gi, to: "menganalisis" },
    { from: /\banalisa\b/gi, to: "menganalisis" },
    { from: /\bevaluasi\b/gi, to: "mengevaluasi" },
    { from: /\bnilai\b/gi, to: "menilai" },
    { from: /\bukur\b/gi, to: "mengukur" },
    { from: /\bhitung\b/gi, to: "menghitung" },
    { from: /\bcatet\b/gi, to: "mencatat" },
    { from: /\bcatat\b/gi, to: "mencatat" },
    { from: /\bdokumentasiin\b/gi, to: "mendokumentasikan" },
    { from: /\bdokumentasi\b/gi, to: "mendokumentasikan" },
    { from: /\bfoto\b/gi, to: "memfoto" },
    { from: /\bvideo\b/gi, to: "merekam video" },
    { from: /\brecord\b/gi, to: "merekam" },
    { from: /\bmonitor\b/gi, to: "memantau" },
    { from: /\bpantau\b/gi, to: "memantau" },
    { from: /\bkontrol\b/gi, to: "mengontrol" },
    { from: /\bawasi\b/gi, to: "mengawasi" },
    { from: /\bmanage\b/gi, to: "mengelola" },
    { from: /\batur\b/gi, to: "mengatur" },
    { from: /\borganisir\b/gi, to: "mengorganisir" },
    { from: /\bkoordinasi\b/gi, to: "berkoordinasi" },
    { from: /\bkolaborasi\b/gi, to: "berkolaborasi" },
    { from: /\bsupport\b/gi, to: "mendukung" },
    { from: /\bbantuin\b/gi, to: "membantu" },
    { from: /\bassist\b/gi, to: "membantu" },
    { from: /\bsupport\b/gi, to: "mendukung" },
    { from: /\bmaintain\b/gi, to: "memelihara" },
    { from: /\braw\b/gi, to: "merawat" },
    { from: /\bupdate\b/gi, to: "memperbarui" },
    { from: /\bupgrade\b/gi, to: "meningkatkan" },
    { from: /\boptimasi\b/gi, to: "mengoptimalkan" },
    { from: /\bimprove\b/gi, to: "meningkatkan" },
    { from: /\bdevelop\b/gi, to: "mengembangkan" },
    { from: /\bkembangin\b/gi, to: "mengembangkan" },
    { from: /\bbuild\b/gi, to: "membangun" },
    { from: /\bcreate\b/gi, to: "membuat" },
    { from: /\bgenerate\b/gi, to: "menghasilkan" },
    { from: /\bproduce\b/gi, to: "menghasilkan" },
    { from: /\bdeliver\b/gi, to: "menyerahkan" },
    { from: /\bsubmit\b/gi, to: "mengumpulkan" },
    { from: /\bkumpul\b/gi, to: "mengumpulkan" },
    { from: /\bcompile\b/gi, to: "mengompilasi" },
    { from: /\bdeploy\b/gi, to: "menerapkan" },
    { from: /\bimplement\b/gi, to: "mengimplementasikan" },
    { from: /\bapply\b/gi, to: "menerapkan" },
    { from: /\buse\b/gi, to: "menggunakan" },
    { from: /\bpakai\b/gi, to: "menggunakan" },
    { from: /\bgunain\b/gi, to: "menggunakan" },
    { from: /\butilize\b/gi, to: "memanfaatkan" },
    { from: /\bleverage\b/gi, to: "memanfaatkan" },
    { from: /\bexplore\b/gi, to: "menjelajahi" },
    { from: /\bresearch\b/gi, to: "meneliti" },
    { from: /\bstudy\b/gi, to: "mempelajari" },
    { from: /\blearn\b/gi, to: "belajar" },
    { from: /\btrain\b/gi, to: "berlatih" },
    { from: /\bpractice\b/gi, to: "berlatih" },
    { from: /\blatih\b/gi, to: "berlatih" },
    { from: /\bexercise\b/gi, to: "berlatih" },
    { from: /\bdrill\b/gi, to: "berlatih" },
    { from: /\brehearse\b/gi, to: "berlatih" },
    { from: /\bprepare\b/gi, to: "mempersiapkan" },
    { from: /\bplan\b/gi, to: "merencanakan" },
    { from: /\bdesign\b/gi, to: "merancang" },
    { from: /\barchitect\b/gi, to: "merancang" },
    { from: /\bstructure\b/gi, to: "menyusun" },
    { from: /\borganize\b/gi, to: "mengorganisir" },
    { from: /\bschedule\b/gi, to: "menjadwalkan" },
    { from: /\barrange\b/gi, to: "mengatur" },
    { from: /\bcoordinate\b/gi, to: "mengkoordinasikan" },
    { from: /\bmanage\b/gi, to: "mengelola" },
    { from: /\blead\b/gi, to: "memimpin" },
    { from: /\bguide\b/gi, to: "membimbing" },
    { from: /\bdirect\b/gi, to: "mengarahkan" },
    { from: /\bsupervise\b/gi, to: "mengawasi" },
    { from: /\boversee\b/gi, to: "mengawasi" },
    { from: /\bmonitor\b/gi, to: "memantau" },
    { from: /\btrack\b/gi, to: "melacak" },
    { from: /\bmeasure\b/gi, to: "mengukur" },
    { from: /\banalyze\b/gi, to: "menganalisis" },
    { from: /\bevaluate\b/gi, to: "mengevaluasi" },
    { from: /\bassess\b/gi, to: "menilai" },
    { from: /\breview\b/gi, to: "meninjau" },
    { from: /\baudit\b/gi, to: "mengaudit" },
    { from: /\binspect\b/gi, to: "memeriksa" },
    { from: /\bexamine\b/gi, to: "memeriksa" },
    { from: /\binvestigate\b/gi, to: "menyelidiki" },
    { from: /\bexplore\b/gi, to: "menjelajahi" },
    { from: /\bdiscover\b/gi, to: "menemukan" },
    { from: /\bidentify\b/gi, to: "mengidentifikasi" },
    { from: /\brecognize\b/gi, to: "mengenali" },
    { from: /\bdetect\b/gi, to: "mendeteksi" },
    { from: /\blocate\b/gi, to: "menemukan" },
    { from: /\bfind\b/gi, to: "menemukan" },
    { from: /\bsearch\b/gi, to: "mencari" },
    { from: /\bseek\b/gi, to: "mencari" },
    { from: /\blook\b/gi, to: "mencari" },
    { from: /\bquery\b/gi, to: "memeriksa" },
    { from: /\bask\b/gi, to: "bertanya" },
    { from: /\binquire\b/gi, to: "bertanya" },
    { from: /\bconsult\b/gi, to: "berkonsultasi" },
    { from: /\bdiscuss\b/gi, to: "berdiskusi" },
    { from: /\bconfer\b/gi, to: "berkonsultasi" },
    { from: /\bmeet\b/gi, to: "bertemu" },
    { from: /\battend\b/gi, to: "menghadiri" },
    { from: /\bjoin\b/gi, to: "bergabung" },
    { from: /\bparticipate\b/gi, to: "berpartisipasi" },
    { from: /\bengage\b/gi, to: "terlibat" },
    { from: /\bcontribute\b/gi, to: "berkontribusi" },
    { from: /\bshare\b/gi, to: "berbagi" },
    { from: /\bcommunicate\b/gi, to: "berkomunikasi" },
    { from: /\binteract\b/gi, to: "berinteraksi" },
    { from: /\bcollaborate\b/gi, to: "berkolaborasi" },
    { from: /\bcooperate\b/gi, to: "bekerja sama" },
    { from: /\bteam\b/gi, to: "bekerja dalam tim" },
    { from: /\bpartner\b/gi, to: "bermitra" },
    { from: /\bally\b/gi, to: "bersekutu" },
    { from: /\bunite\b/gi, to: "bersatu" },
    { from: /\bcombine\b/gi, to: "menggabungkan" },
    { from: /\bmerge\b/gi, to: "menggabungkan" },
    { from: /\bintegrate\b/gi, to: "mengintegrasikan" },
    { from: /\bsync\b/gi, to: "menyelaraskan" },
    { from: /\balien\b/gi, to: "menyelaraskan" },
    { from: /\bharmonize\b/gi, to: "menyelaraskan" },
    { from: /\bbalance\b/gi, to: "menyeimbangkan" },
    { from: /\bstabilize\b/gi, to: "menstabilkan" },
    { from: /\bnormalize\b/gi, to: "menormalkan" },
    { from: /\bstandardize\b/gi, to: "menstandarkan" },
    { from: /\boptimize\b/gi, to: "mengoptimalkan" },
    { from: /\bmaximize\b/gi, to: "memaksimalkan" },
    { from: /\bminimize\b/gi, to: "meminimalkan" },
    { from: /\breduce\b/gi, to: "mengurangi" },
    { from: /\bdecrease\b/gi, to: "mengurangi" },
    { from: /\bincrease\b/gi, to: "meningkatkan" },
    { from: /\bboost\b/gi, to: "meningkatkan" },
    { from: /\benhance\b/gi, to: "meningkatkan" },
    { from: /\bimprove\b/gi, to: "meningkatkan" },
    { from: /\bupgrade\b/gi, to: "meningkatkan" },
    { from: /\badvance\b/gi, to: "memajukan" },
    { from: /\bprogress\b/gi, to: "berkembang" },
    { from: /\bevolve\b/gi, to: "berkembang" },
    { from: /\bgrow\b/gi, to: "berkembang" },
    { from: /\bexpand\b/gi, to: "memperluas" },
    { from: /\bstretch\b/gi, to: "memperluas" },
    { from: /\bextend\b/gi, to: "memperpanjang" },
    { from: /\bprolong\b/gi, to: "memperpanjang" },
    { from: /\bcontinue\b/gi, to: "melanjutkan" },
    { from: /\bmaintain\b/gi, to: "mempertahankan" },
    { from: /\bsustain\b/gi, to: "mempertahankan" },
    { from: /\bpreserve\b/gi, to: "melestarikan" },
    { from: /\bprotect\b/gi, to: "melindungi" },
    { from: /\bsafeguard\b/gi, to: "melindungi" },
    { from: /\bsecure\b/gi, to: "mengamankan" },
    { from: /\bdefend\b/gi, to: "mempertahankan" },
    { from: /\bguard\b/gi, to: "menjaga" },
    { from: /\bwatch\b/gi, to: "mengawasi" },
    { from: /\bobserve\b/gi, to: "mengamati" },
    { from: /\bnotice\b/gi, to: "memperhatikan" },
    { from: /\bnote\b/gi, to: "mencatat" },
    { from: /\brecord\b/gi, to: "mencatat" },
    { from: /\bdocument\b/gi, to: "mendokumentasikan" },
    { from: /\breport\b/gi, to: "melaporkan" },
    { from: /\bnotify\b/gi, to: "memberitahu" },
    { from: /\binform\b/gi, to: "menginformasikan" },
    { from: /\bbrief\b/gi, to: "memberi pengarahan" },
    { from: /\bupdate\b/gi, to: "memperbarui" },
    { from: /\brefresh\b/gi, to: "menyegarkan" },
    { from: /\brenew\b/gi, to: "memperbarui" },
    { from: /\brestore\b/gi, to: "memulihkan" },
    { from: /\brecover\b/gi, to: "memulihkan" },
    { from: /\brepair\b/gi, to: "memperbaiki" },
    { from: /\bfix\b/gi, to: "memperbaiki" },
    { from: /\bmend\b/gi, to: "memperbaiki" },
    { from: /\bcorrect\b/gi, to: "memperbaiki" },
    { from: /\badjust\b/gi, to: "menyesuaikan" },
    { from: /\badapt\b/gi, to: "menyesuaikan" },
    { from: /\bmodify\b/gi, to: "memodifikasi" },
    { from: /\balter\b/gi, to: "mengubah" },
    { from: /\bchange\b/gi, to: "mengubah" },
    { from: /\btransform\b/gi, to: "mengubah" },
    { from: /\bconvert\b/gi, to: "mengonversi" },
    { from: /\btranslate\b/gi, to: "menerjemahkan" },
    { from: /\binterpret\b/gi, to: "menafsirkan" },
    { from: /\bexplain\b/gi, to: "menjelaskan" },
    { from: /\bclarify\b/gi, to: "menjelaskan" },
    { from: /\billustrate\b/gi, to: "mengilustrasikan" },
    { from: /\bdemonstrate\b/gi, to: "mendemonstrasikan" },
    { from: /\bshow\b/gi, to: "menunjukkan" },
    { from: /\bdisplay\b/gi, to: "menampilkan" },
    { from: /\bpresent\b/gi, to: "mempresentasikan" },
    { from: /\bexhibit\b/gi, to: "memamerkan" },
    { from: /\bexpose\b/gi, to: "memaparkan" },
    { from: /\breveal\b/gi, to: "mengungkapkan" },
    { from: /\bdisclose\b/gi, to: "mengungkapkan" },
    { from: /\buncover\b/gi, to: "mengungkap" },
    { from: /\bdiscover\b/gi, to: "menemukan" },
    { from: /\bunveil\b/gi, to: "mengungkap" },
    { from: /\blauch\b/gi, to: "meluncurkan" },
    { from: /\bstart\b/gi, to: "memulai" },
    { from: /\bbegin\b/gi, to: "memulai" },
    { from: /\bcommence\b/gi, to: "memulai" },
    { from: /\binitiate\b/gi, to: "memulai" },
    { from: /\blaunch\b/gi, to: "meluncurkan" },
    { from: /\btrigger\b/gi, to: "memicu" },
    { from: /\bactivate\b/gi, to: "mengaktifkan" },
    { from: /\benable\b/gi, to: "mengaktifkan" },
    { from: /\bturn on\b/gi, to: "mengaktifkan" },
    { from: /\bpower on\b/gi, to: "menghidupkan" },
    { from: /\boot\b/gi, to: "menyalakan" },
    { from: /\brun\b/gi, to: "menjalankan" },
    { from: /\bexecute\b/gi, to: "menjalankan" },
    { from: /\bperform\b/gi, to: "melakukan" },
    { from: /\bdo\b/gi, to: "melakukan" },
    { from: /\bact\b/gi, to: "bertindak" },
    { from: /\boperate\b/gi, to: "mengoperasikan" },
    { from: /\bhandle\b/gi, to: "menangani" },
    { from: /\bdeal\b/gi, to: "menangani" },
    { from: /\bmanage\b/gi, to: "mengelola" },
    { from: /\bcontrol\b/gi, to: "mengontrol" },
    { from: /\bdirect\b/gi, to: "mengarahkan" },
    { from: /\bguide\b/gi, to: "membimbing" },
    { from: /\blead\b/gi, to: "memimpin" },
    { from: /\bhead\b/gi, to: "memimpin" },
    { from: /\bmanage\b/gi, to: "mengelola" },
    { from: /\bsupervise\b/gi, to: "mengawasi" },
    { from: /\boversee\b/gi, to: "mengawasi" },
    { from: /\bmonitor\b/gi, to: "memantau" },
    { from: /\btrack\b/gi, to: "melacak" },
    { from: /\bfollow\b/gi, to: "mengikuti" },
    { from: /\bpursue\b/gi, to: "mengejar" },
    { from: /\bchase\b/gi, to: "mengejar" },
    { from: /\bseek\b/gi, to: "mencari" },
    { from: /\bsearch\b/gi, to: "mencari" },
    { from: /\bfind\b/gi, to: "menemukan" },
    { from: /\blocate\b/gi, to: "menemukan" },
    { from: /\bdetect\b/gi, to: "mendeteksi" },
    { from: /\bidentify\b/gi, to: "mengidentifikasi" },
    { from: /\brecognize\b/gi, to: "mengenali" },
    { from: /\bdistinguish\b/gi, to: "membedakan" },
    { from: /\bdifferentiate\b/gi, to: "membedakan" },
    { from: /\bcompare\b/gi, to: "membandingkan" },
    { from: /\bcontrast\b/gi, to: "membandingkan" },
    { from: /\bmatch\b/gi, to: "mencocokkan" },
    { from: /\balign\b/gi, to: "menyelaraskan" },
    { from: /\bsynchronize\b/gi, to: "menyelaraskan" },
    { from: /\bcoordinate\b/gi, to: "mengkoordinasikan" },
    { from: /\borganize\b/gi, to: "mengorganisir" },
    { from: /\barrange\b/gi, to: "mengatur" },
    { from: /\bsort\b/gi, to: "menyortir" },
    { from: /\bclassify\b/gi, to: "mengklasifikasikan" },
    { from: /\bcategorize\b/gi, to: "mengategorikan" },
    { from: /\bgroup\b/gi, to: "mengelompokkan" },
    { from: /\bcluster\b/gi, to: "mengelompokkan" },
    { from: /\bbundle\b/gi, to: "mengelompokkan" },
    { from: /\bpackage\b/gi, to: "mengemas" },
    { from: /\bwrap\b/gi, to: "membungkus" },
    { from: /\bcover\b/gi, to: "menutupi" },
    { from: /\bprotect\b/gi, to: "melindungi" },
    { from: /\bshield\b/gi, to: "melindungi" },
    { from: /\bdefend\b/gi, to: "mempertahankan" },
    { from: /\bsecure\b/gi, to: "mengamankan" },
    { from: /\bsafe\b/gi, to: "mengamankan" },
    { from: /\bsave\b/gi, to: "menyimpan" },
    { from: /\bstore\b/gi, to: "menyimpan" },
    { from: /\bkeep\b/gi, to: "menyimpan" },
    { from: /\bretain\b/gi, to: "mempertahankan" },
    { from: /\bhold\b/gi, to: "memegang" },
    { from: /\bgrasp\b/gi, to: "memegang" },
    { from: /\bgrip\b/gi, to: "memegang" },
    { from: /\bclutch\b/gi, to: "memegang" },
    { from: /\bseize\b/gi, to: "merebut" },
    { from: /\bcapture\b/gi, to: "menangkap" },
    { from: /\bcatch\b/gi, to: "menangkap" },
    { from: /\btrap\b/gi, to: "menjebak" },
    { from: /\bsnare\b/gi, to: "menjebak" },
    { from: /\bentrap\b/gi, to: "menjebak" },
    { from: /\bconfine\b/gi, to: "membatasi" },
    { from: /\brestrict\b/gi, to: "membatasi" },
    { from: /\blimit\b/gi, to: "membatasi" },
    { from: /\bbound\b/gi, to: "membatasi" },
    { from: /\bconstrain\b/gi, to: "membatasi" },
    { from: /\bcontrol\b/gi, to: "mengontrol" },
    { from: /\bregulate\b/gi, to: "mengatur" },
    { from: /\bgovern\b/gi, to: "mengatur" },
    { from: /\brule\b/gi, to: "mengatur" },
    { from: /\bcommand\b/gi, to: "memerintah" },
    { from: /\border\b/gi, to: "memerintahkan" },
    { from: /\bdirect\b/gi, to: "mengarahkan" },
    { from: /\binstruct\b/gi, to: "menginstruksikan" },
    { from: /\bteach\b/gi, to: "mengajar" },
    { from: /\beducate\b/gi, to: "mendidik" },
    { from: /\btrain\b/gi, to: "melatih" },
    { from: /\bcoach\b/gi, to: "melatih" },
    { from: /\bmentor\b/gi, to: "membimbing" },
    { from: /\btutor\b/gi, to: "mengajar" },
    { from: /\bguide\b/gi, to: "membimbing" },
    { from: /\blead\b/gi, to: "memimpin" },
    { from: /\bshow\b/gi, to: "menunjukkan" },
    { from: /\bdemonstrate\b/gi, to: "mendemonstrasikan" },
    { from: /\billustrate\b/gi, to: "mengilustrasikan" },
    { from: /\bexemplify\b/gi, to: "memberi contoh" },
    { from: /\bmodel\b/gi, to: "memodelkan" },
    { from: /\bsimulate\b/gi, to: "mensimulasikan" },
    { from: /\bmimic\b/gi, to: "meniru" },
    { from: /\bcopy\b/gi, to: "menyalin" },
    { from: /\bduplicate\b/gi, to: "menduplikasi" },
    { from: /\breproduce\b/gi, to: "mereproduksi" },
    { from: /\breplicate\b/gi, to: "mereplikasi" },
    { from: /\bclone\b/gi, to: "mengkloning" },
    { from: /\bmirror\b/gi, to: "mencerminkan" },
    { from: /\breflect\b/gi, to: "mencerminkan" },
    { from: /\becho\b/gi, to: "menggemakan" },
    { from: /\brepeat\b/gi, to: "mengulang" },
    { from: /\biterate\b/gi, to: "mengulang" },
    { from: /\bcycle\b/gi, to: "berputar" },
    { from: /\brotate\b/gi, to: "berputar" },
    { from: /\bspin\b/gi, to: "berputar" },
    { from: /\bturn\b/gi, to: "berputar" },
    { from: /\brevolve\b/gi, to: "berputar" },
    { from: /\borbit\b/gi, to: "mengorbit" },
    { from: /\bcircle\b/gi, to: "mengelilingi" },
    { from: /\bsurround\b/gi, to: "mengelilingi" },
    { from: /\bencircle\b/gi, to: "mengelilingi" },
    { from: /\bencompass\b/gi, to: "mencakup" },
    { from: /\binclude\b/gi, to: "mencakup" },
    { from: /\bcontain\b/gi, to: "mengandung" },
    { from: /\bcomprise\b/gi, to: "terdiri dari" },
    { from: /\bconsist\b/gi, to: "terdiri dari" },
    { from: /\bcompose\b/gi, to: "menyusun" },
    { from: /\bconstitute\b/gi, to: "membentuk" },
    { from: /\bform\b/gi, to: "membentuk" },
    { from: /\bshape\b/gi, to: "membentuk" },
    { from: /\bmold\b/gi, to: "membentuk" },
    { from: /\bforge\b/gi, to: "membentuk" },
    { from: /\bfashion\b/gi, to: "membentuk" },
    { from: /\bcraft\b/gi, to: "membuat" },
    { from: /\bbuild\b/gi, to: "membangun" },
    { from: /\bconstruct\b/gi, to: "membangun" },
    { from: /\berect\b/gi, to: "membangun" },
    { from: /\bassemble\b/gi, to: "merakit" },
    { from: /\bmanufacture\b/gi, to: "memproduksi" },
    { from: /\bproduce\b/gi, to: "menghasilkan" },
    { from: /\bgenerate\b/gi, to: "menghasilkan" },
    { from: /\bcreate\b/gi, to: "membuat" },
    { from: /\bmake\b/gi, to: "membuat" },
    { from: /\bfabricate\b/gi, to: "membuat" },
    { from: /\bconstruct\b/gi, to: "membangun" },
    { from: /\bdevelop\b/gi, to: "mengembangkan" },
    { from: /\bdesign\b/gi, to: "merancang" },
    { from: /\bplan\b/gi, to: "merencanakan" },
    { from: /\bprepare\b/gi, to: "mempersiapkan" },
    { from: /\barrange\b/gi, to: "mengatur" },
    { from: /\borganize\b/gi, to: "mengorganisir" },
    { from: /\bset up\b/gi, to: "mempersiapkan" },
    { from: /\bestablish\b/gi, to: "menetapkan" },
    { from: /\binstitute\b/gi, to: "melembagakan" },
    { from: /\bfound\b/gi, to: "mendirikan" },
    { from: /\bstart\b/gi, to: "memulai" },
    { from: /\bbegin\b/gi, to: "memulai" },
    { from: /\binitiate\b/gi, to: "memulai" },
    { from: /\bcommence\b/gi, to: "memulai" },
    { from: /\blauch\b/gi, to: "meluncurkan" },
    { from: /\bintroduce\b/gi, to: "memperkenalkan" },
    { from: /\bpresent\b/gi, to: "mempresentasikan" },
    { from: /\boffer\b/gi, to: "menawarkan" },
    { from: /\bprovide\b/gi, to: "menyediakan" },
    { from: /\bsupply\b/gi, to: "menyediakan" },
    { from: /\bdeliver\b/gi, to: "menyerahkan" },
    { from: /\bhand\b/gi, to: "menyerahkan" },
    { from: /\bpass\b/gi, to: "melewati" },
    { from: /\btransfer\b/gi, to: "mentransfer" },
    { from: /\bmove\b/gi, to: "memindahkan" },
    { from: /\bshift\b/gi, to: "menggeser" },
    { from: /\btransport\b/gi, to: "mengangkut" },
    { from: /\bcarry\b/gi, to: "membawa" },
    { from: /\bbear\b/gi, to: "membawa" },
    { from: /\bbring\b/gi, to: "membawa" },
    { from: /\bfetch\b/gi, to: "mengambil" },
    { from: /\bget\b/gi, to: "mendapatkan" },
    { from: /\bobtain\b/gi, to: "mendapatkan" },
    { from: /\bacquire\b/gi, to: "memperoleh" },
    { from: /\bgain\b/gi, to: "mendapatkan" },
    { from: /\bearn\b/gi, to: "mendapatkan" },
    { from: /\bwin\b/gi, to: "memenangkan" },
    { from: /\bachieve\b/gi, to: "mencapai" },
    { from: /\battain\b/gi, to: "mencapai" },
    { from: /\breach\b/gi, to: "mencapai" },
    { from: /\barrive\b/gi, to: "tiba" },
    { from: /\bcome\b/gi, to: "datang" },
    { from: /\bgo\b/gi, to: "pergi" },
    { from: /\bleave\b/gi, to: "meninggalkan" },
    { from: /\bdepart\b/gi, to: "berangkat" },
    { from: /\bexit\b/gi, to: "keluar" },
    { from: /\benter\b/gi, to: "masuk" },
    { from: /\bjoin\b/gi, to: "bergabung" },
    { from: /\bparticipate\b/gi, to: "berpartisipasi" },
    { from: /\btake part\b/gi, to: "berpartisipasi" },
    { from: /\bengage\b/gi, to: "terlibat" },
    { from: /\binvolve\b/gi, to: "melibatkan" },
    { from: /\binclude\b/gi, to: "mencakup" },
    { from: /\bincorporate\b/gi, to: "menggabungkan" },
    { from: /\bintegrate\b/gi, to: "mengintegrasikan" },
    { from: /\bmerge\b/gi, to: "menggabungkan" },
    { from: /\bcombine\b/gi, to: "menggabungkan" },
    { from: /\bunite\b/gi, to: "menyatukan" },
    { from: /\bconnect\b/gi, to: "menghubungkan" },
    { from: /\blink\b/gi, to: "menghubungkan" },
    { from: /\bjoin\b/gi, to: "menyambungkan" },
    { from: /\battach\b/gi, to: "melampirkan" },
    { from: /\bfasten\b/gi, to: "mengikat" },
    { from: /\bsecure\b/gi, to: "mengamankan" },
    { from: /\bfix\b/gi, to: "memperbaiki" },
    { from: /\brepair\b/gi, to: "memperbaiki" },
    { from: /\bmend\b/gi, to: "memperbaiki" },
    { from: /\brestore\b/gi, to: "memulihkan" },
    { from: /\brecover\b/gi, to: "memulihkan" },
    { from: /\bheal\b/gi, to: "menyembuhkan" },
    { from: /\bcure\b/gi, to: "menyembuhkan" },
    { from: /\btreat\b/gi, to: "merawat" },
    { from: /\bcare\b/gi, to: "merawat" },
    { from: /\bnurse\b/gi, to: "merawat" },
    { from: /\btend\b/gi, to: "merawat" },
    { from: /\blook after\b/gi, to: "merawat" },
    { from: /\bmaintain\b/gi, to: "memelihara" },
    { from: /\bsustain\b/gi, to: "mempertahankan" },
    { from: /\bsupport\b/gi, to: "mendukung" },
    { from: /\back\b/gi, to: "mendukung" },
    { from: /\bendorse\b/gi, to: "mendukung" },
    { from: /\bbolster\b/gi, to: "mendukung" },
    { from: /\breinforce\b/gi, to: "memperkuat" },
    { from: /\bstrengthen\b/gi, to: "memperkuat" },
    { from: /\bfortify\b/gi, to: "memperkuat" },
    { from: /\bbolster\b/gi, to: "memperkuat" },
    { from: /\benhance\b/gi, to: "meningkatkan" },
    { from: /\bimprove\b/gi, to: "meningkatkan" },
    { from: /\bupgrade\b/gi, to: "meningkatkan" },
    { from: /\bboost\b/gi, to: "meningkatkan" },
    { from: /\belevate\b/gi, to: "meningkatkan" },
    { from: /\braise\b/gi, to: "meningkatkan" },
    { from: /\blift\b/gi, to: "mengangkat" },
    { from: /\bhoist\b/gi, to: "mengangkat" },
    { from: /\bheave\b/gi, to: "mengangkat" },
    { from: /\bpush\b/gi, to: "mendorong" },
    { from: /\bshove\b/gi, to: "mendorong" },
    { from: /\bthrust\b/gi, to: "mendorong" },
    { from: /\bpull\b/gi, to: "menarik" },
    { from: /\btug\b/gi, to: "menarik" },
    { from: /\byank\b/gi, to: "menarik" },
    { from: /\bdrag\b/gi, to: "menyeret" },
    { from: /\bhaul\b/gi, to: "menyeret" },
    { from: /\btow\b/gi, to: "menarik" },
    { from: /\bdraw\b/gi, to: "menggambar" },
    { from: /\bsketch\b/gi, to: "membuat sketsa" },
    { from: /\bpaint\b/gi, to: "melukis" },
    { from: /\bcolor\b/gi, to: "mewarnai" },
    { from: /\bshade\b/gi, to: "membayangi" },
    { from: /\btint\b/gi, to: "mewarnai" },
    { from: /\bdye\b/gi, to: "mencelup" },
    { from: /\bstain\b/gi, to: "mewarnai" },
    { from: /\bprint\b/gi, to: "mencetak" },
    { from: /\bpublish\b/gi, to: "menerbitkan" },
    { from: /\bissue\b/gi, to: "menerbitkan" },
    { from: /\brelease\b/gi, to: "merilis" },
    { from: /\blauch\b/gi, to: "meluncurkan" },
    { from: /\bdistribute\b/gi, to: "mendistribusikan" },
    { from: /\bcirculate\b/gi, to: "mengedarkan" },
    { from: /\bspread\b/gi, to: "menyebarkan" },
    { from: /\bdisseminate\b/gi, to: "menyebarluaskan" },
    { from: /\bbroadcast\b/gi, to: "menyiarkan" },
    { from: /\btransmit\b/gi, to: "mentransmisikan" },
    { from: /\bsend\b/gi, to: "mengirim" },
    { from: /\bdispatch\b/gi, to: "mengirim" },
    { from: /\bforward\b/gi, to: "meneruskan" },
    { from: /\brelay\b/gi, to: "meneruskan" },
    { from: /\bpass on\b/gi, to: "meneruskan" },
    { from: /\bcommunicate\b/gi, to: "berkomunikasi" },
    { from: /\bconvey\b/gi, to: "menyampaikan" },
    { from: /\bexpress\b/gi, to: "menyatakan" },
    { from: /\bstate\b/gi, to: "menyatakan" },
    { from: /\bdeclare\b/gi, to: "menyatakan" },
    { from: /\bannounce\b/gi, to: "mengumumkan" },
    { from: /\bproclaim\b/gi, to: "memproklamasikan" },
    { from: /\bpublish\b/gi, to: "menerbitkan" },
    { from: /\bpost\b/gi, to: "memposting" },
    { from: /\bupload\b/gi, to: "mengunggah" },
    { from: /\bshare\b/gi, to: "berbagi" },
    { from: /\bdistribute\b/gi, to: "mendistribusikan" },
    { from: /\ballocate\b/gi, to: "mengalokasikan" },
    { from: /\bassign\b/gi, to: "menugaskan" },
    { from: /\bdelegate\b/gi, to: "mendelegasikan" },
    { from: /\bentrust\b/gi, to: "mempercayakan" },
    { from: /\bcommit\b/gi, to: "mengkomitmen" },
    { from: /\bpledge\b/gi, to: "berjanji" },
    { from: /\bpromise\b/gi, to: "berjanji" },
    { from: /\bvow\b/gi, to: "bersumpah" },
    { from: /\bswear\b/gi, to: "bersumpah" },
    { from: /\baffirm\b/gi, to: "menegaskan" },
    { from: /\bassert\b/gi, to: "menegaskan" },
    { from: /\bmaintain\b/gi, to: "mempertahankan" },
    { from: /\bcontend\b/gi, to: "berargumen" },
    { from: /\bargue\b/gi, to: "berargumen" },
    { from: /\bdebate\b/gi, to: "berdebat" },
    { from: /\bdiscuss\b/gi, to: "berdiskusi" },
    { from: /\bnegotiate\b/gi, to: "bernegosiasi" },
    { from: /\bbargain\b/gi, to: "bernegosiasi" },
    { from: /\bhaggle\b/gi, to: "bernegosiasi" },
    { from: /\bmediate\b/gi, to: "menengahi" },
    { from: /\barbitrate\b/gi, to: "menengahi" },
    { from: /\badjudicate\b/gi, to: "mengadili" },
    { from: /\bjudge\b/gi, to: "menilai" },
    { from: /\bevaluate\b/gi, to: "mengevaluasi" },
    { from: /\bassess\b/gi, to: "menilai" },
    { from: /\bappraise\b/gi, to: "menilai" },
    { from: /\bestimate\b/gi, to: "memperkirakan" },
    { from: /\bcalculate\b/gi, to: "menghitung" },
    { from: /\bcompute\b/gi, to: "menghitung" },
    { from: /\breckon\b/gi, to: "menghitung" },
    { from: /\bfigure\b/gi, to: "menghitung" },
    { from: /\btally\b/gi, to: "menghitung" },
    { from: /\bcount\b/gi, to: "menghitung" },
    { from: /\benumerate\b/gi, to: "menghitung" },
    { from: /\blist\b/gi, to: "mencantumkan" },
    { from: /\bcatalog\b/gi, to: "mengkatalog" },
    { from: /\bindex\b/gi, to: "mengindeks" },
    { from: /\bregister\b/gi, to: "mendaftarkan" },
    { from: /\brecord\b/gi, to: "mencatat" },
    { from: /\bdocument\b/gi, to: "mendokumentasikan" },
    { from: /\barchive\b/gi, to: "mengarsipkan" },
    { from: /\bfile\b/gi, to: "mengarsipkan" },
    { from: /\bstore\b/gi, to: "menyimpan" },
    { from: /\bsave\b/gi, to: "menyimpan" },
    { from: /\bkeep\b/gi, to: "menyimpan" },
    { from: /\bretain\b/gi, to: "mempertahankan" },
    { from: /\bhold\b/gi, to: "memegang" },
    { from: /\bpossess\b/gi, to: "memiliki" },
    { from: /\bown\b/gi, to: "memiliki" },
    { from: /\bhave\b/gi, to: "memiliki" },
    { from: /\bbelong\b/gi, to: "milik" },
    { from: /\bpertain\b/gi, to: "terkait" },
    { from: /\brelate\b/gi, to: "terkait" },
    { from: /\bconnect\b/gi, to: "terhubung" },
    { from: /\bassociate\b/gi, to: "mengasosiasikan" },
    { from: /\blink\b/gi, to: "menghubungkan" },
    { from: /\btie\b/gi, to: "mengikat" },
    { from: /\bbind\b/gi, to: "mengikat" },
    { from: /\battach\b/gi, to: "melampirkan" },
    { from: /\baffix\b/gi, to: "melampirkan" },
    { from: /\bappend\b/gi, to: "melampirkan" },
    { from: /\badd\b/gi, to: "menambahkan" },
    { from: /\binsert\b/gi, to: "menyisipkan" },
    { from: /\binclude\b/gi, to: "mencakup" },
    { from: /\bincorporate\b/gi, to: "menggabungkan" },
    { from: /\bintegrate\b/gi, to: "mengintegrasikan" },
    { from: /\bmerge\b/gi, to: "menggabungkan" },
    { from: /\bcombine\b/gi, to: "menggabungkan" },
    { from: /\bblend\b/gi, to: "mencampur" },
    { from: /\bmix\b/gi, to: "mencampur" },
    { from: /\bmingle\b/gi, to: "mencampur" },
    { from: /\bfuse\b/gi, to: "melebur" },
    { from: /\bweld\b/gi, to: "mengelas" },
    { from: /\bsolder\b/gi, to: "menyolder" },
    { from: /\bbraze\b/gi, to: "memateri" },
    { from: /\bglue\b/gi, to: "mengelem" },
    { from: /\bstick\b/gi, to: "menempel" },
    { from: /\badhere\b/gi, to: "menempel" },
    { from: /\bcling\b/gi, to: "melekat" },
    { from: /\bbond\b/gi, to: "mengikat" },
    { from: /\bunite\b/gi, to: "menyatukan" },
    { from: /\bjoin\b/gi, to: "menyambungkan" },
    { from: /\bconnect\b/gi, to: "menghubungkan" },
    { from: /\blink\b/gi, to: "menghubungkan" },
    { from: /\bbridge\b/gi, to: "menjembatani" },
    { from: /\bspan\b/gi, to: "melintasi" },
    { from: /\bcross\b/gi, to: "menyeberang" },
    { from: /\btraverse\b/gi, to: "melintasi" },
    { from: /\bnavigate\b/gi, to: "menavigasi" },
    { from: /\bpilot\b/gi, to: "memandu" },
    { from: /\bsteer\b/gi, to: "mengemudikan" },
    { from: /\bdrive\b/gi, to: "mengemudikan" },
    { from: /\boperate\b/gi, to: "mengoperasikan" },
    { from: /\bcontrol\b/gi, to: "mengontrol" },
    { from: /\bmanage\b/gi, to: "mengelola" },
    { from: /\bhandle\b/gi, to: "menangani" },
    { from: /\bdeal\b/gi, to: "menangani" },
    { from: /\btackle\b/gi, to: "menangani" },
    { from: /\baddress\b/gi, to: "mengatasi" },
    { from: /\bresolve\b/gi, to: "menyelesaikan" },
    { from: /\bsolve\b/gi, to: "menyelesaikan" },
    { from: /\bfix\b/gi, to: "memperbaiki" },
    { from: /\brepair\b/gi, to: "memperbaiki" },
    { from: /\bmend\b/gi, to: "memperbaiki" },
    { from: /\bpatch\b/gi, to: "menambal" },
    { from: /\bdarn\b/gi, to: "menambal" },
    { from: /\bstitch\b/gi, to: "menjahit" },
    { from: /\bsew\b/gi, to: "menjahit" },
    { from: /\bknit\b/gi, to: "merajut" },
    { from: /\bweave\b/gi, to: "menenun" },
    { from: /\bspin\b/gi, to: "memintal" },
    { from: /\btwist\b/gi, to: "memutar" },
    { from: /\bcoil\b/gi, to: "menggulung" },
    { from: /\bwind\b/gi, to: "menggulung" },
    { from: /\bwrap\b/gi, to: "membungkus" },
    { from: /\bcover\b/gi, to: "menutupi" },
    { from: /\benclose\b/gi, to: "menutup" },
    { from: /\bsurround\b/gi, to: "mengelilingi" },
    { from: /\bencompass\b/gi, to: "mencakup" },
    { from: /\bcontain\b/gi, to: "mengandung" },
    { from: /\bhold\b/gi, to: "memuat" },
    { from: /\baccommodate\b/gi, to: "menampung" },
    { from: /\bhouse\b/gi, to: "menampung" },
    { from: /\blodge\b/gi, to: "menampung" },
    { from: /\bshelter\b/gi, to: "melindungi" },
    { from: /\bprotect\b/gi, to: "melindungi" },
    { from: /\bdefend\b/gi, to: "mempertahankan" },
    { from: /\bguard\b/gi, to: "menjaga" },
    { from: /\bwatch\b/gi, to: "mengawasi" },
    { from: /\bobserve\b/gi, to: "mengamati" },
    { from: /\bmonitor\b/gi, to: "memantau" },
    { from: /\bsurveil\b/gi, to: "mengawasi" },
    { from: /\bscout\b/gi, to: "mengintai" },
    { from: /\bspy\b/gi, to: "memata-matai" },
    { from: /\binvestigate\b/gi, to: "menyelidiki" },
    { from: /\bexamine\b/gi, to: "memeriksa" },
    { from: /\binspect\b/gi, to: "memeriksa" },
    { from: /\bcheck\b/gi, to: "memeriksa" },
    { from: /\bverify\b/gi, to: "memverifikasi" },
    { from: /\bconfirm\b/gi, to: "mengonfirmasi" },
    { from: /\bvalidate\b/gi, to: "memvalidasi" },
    { from: /\bauthenticate\b/gi, to: "mengautentikasi" },
    { from: /\bcertify\b/gi, to: "mensertifikasi" },
    { from: /\bapprove\b/gi, to: "menyetujui" },
    { from: /\bendorse\b/gi, to: "mendukung" },
    { from: /\bsanction\b/gi, to: "menyetujui" },
    { from: /\bauthorize\b/gi, to: "mengotorisasi" },
    { from: /\bpermit\b/gi, to: "mengizinkan" },
    { from: /\ballow\b/gi, to: "mengizinkan" },
    { from: /\blet\b/gi, to: "membiarkan" },
    { from: /\bgrant\b/gi, to: "memberikan" },
    { from: /\bbestow\b/gi, to: "memberikan" },
    { from: /\bconfer\b/gi, to: "memberikan" },
    { from: /\baward\b/gi, to: "memberikan" },
    { from: /\bpresent\b/gi, to: "memberikan" },
    { from: /\bgive\b/gi, to: "memberikan" },
    { from: /\bdonate\b/gi, to: "menyumbangkan" },
    { from: /\bcontribute\b/gi, to: "berkontribusi" },
    { from: /\bsubscribe\b/gi, to: "berlangganan" },
    { from: /\bsupport\b/gi, to: "mendukung" },
    { from: /\bfund\b/gi, to: "mendanai" },
    { from: /\bsponsor\b/gi, to: "mensponsori" },
    { from: /\bfinance\b/gi, to: "membiayai" },
    { from: /\bbankroll\b/gi, to: "membiayai" },
    { from: /\bback\b/gi, to: "mendukung" },
    { from: /\bchampion\b/gi, to: "memperjuangkan" },
    { from: /\badvocate\b/gi, to: "menganjurkan" },
    { from: /\bpromote\b/gi, to: "mempromosikan" },
    { from: /\badvertise\b/gi, to: "mengiklankan" },
    { from: /\bmarket\b/gi, to: "memasarkan" },
    { from: /\bsell\b/gi, to: "menjual" },
    { from: /\bvend\b/gi, to: "menjual" },
    { from: /\bretail\b/gi, to: "menjual eceran" },
    { from: /\bwholesale\b/gi, to: "menjual grosir" },
    { from: /\bdistribute\b/gi, to: "mendistribusikan" },
    { from: /\bsupply\b/gi, to: "menyediakan" },
    { from: /\bprovide\b/gi, to: "menyediakan" },
    { from: /\bfurnish\b/gi, to: "menyediakan" },
    { from: /\bequip\b/gi, to: "melengkapi" },
    { from: /\boutfit\b/gi, to: "melengkapi" },
    { from: /\barm\b/gi, to: "melengkapi" },
    { from: /\bprepare\b/gi, to: "mempersiapkan" },
    { from: /\bready\b/gi, to: "mempersiapkan" },
    { from: /\bset\b/gi, to: "menyiapkan" },
    { from: /\barrange\b/gi, to: "mengatur" },
    { from: /\borganize\b/gi, to: "mengorganisir" },
    { from: /\bplan\b/gi, to: "merencanakan" },
    { from: /\bdesign\b/gi, to: "merancang" },
    { from: /\bdevise\b/gi, to: "merancang" },
    { from: /\binvent\b/gi, to: "menemukan" },
    { from: /\bcreate\b/gi, to: "menciptakan" },
    { from: /\boriginate\b/gi, to: "menciptakan" },
    { from: /\bpioneer\b/gi, to: "merintis" },
    { from: /\binitiate\b/gi, to: "memulai" },
    { from: /\bstart\b/gi, to: "memulai" },
    { from: /\bbegin\b/gi, to: "memulai" },
    { from: /\bcommence\b/gi, to: "memulai" },
    { from: /\blauch\b/gi, to: "meluncurkan" },
    { from: /\bembark\b/gi, to: "memulai" },
    { from: /\bundertake\b/gi, to: "melakukan" },
    { from: /\btackle\b/gi, to: "menangani" },
    { from: /\bapproach\b/gi, to: "mendekati" },
    { from: /\baddress\b/gi, to: "mengatasi" },
    { from: /\bconfront\b/gi, to: "menghadapi" },
    { from: /\bface\b/gi, to: "menghadapi" },
    { from: /\bencounter\b/gi, to: "bertemu" },
    { from: /\bmeet\b/gi, to: "bertemu" },
    { from: /\bgreet\b/gi, to: "menyapa" },
    { from: /\bwelcome\b/gi, to: "menyambut" },
    { from: /\breceive\b/gi, to: "menerima" },
    { from: /\baccept\b/gi, to: "menerima" },
    { from: /\btake\b/gi, to: "mengambil" },
    { from: /\bgrab\b/gi, to: "merebut" },
    { from: /\bseize\b/gi, to: "merebut" },
    { from: /\bcapture\b/gi, to: "menangkap" },
    { from: /\bcatch\b/gi, to: "menangkap" },
    { from: /\btrap\b/gi, to: "menjebak" },
    { from: /\bsnare\b/gi, to: "menjebak" },
    { from: /\bentrap\b/gi, to: "menjebak" },
    { from: /\bconfine\b/gi, to: "membatasi" },
    { from: /\brestrict\b/gi, to: "membatasi" },
    { from: /\blimit\b/gi, to: "membatasi" },
    { from: /\bbound\b/gi, to: "membatasi" },
    { from: /\bconstrain\b/gi, to: "membatasi" },
    { from: /\bcontrol\b/gi, to: "mengontrol" },
    { from: /\bregulate\b/gi, to: "mengatur" },
    { from: /\bgovern\b/gi, to: "mengatur" },
    { from: /\brule\b/gi, to: "mengatur" },
    { from: /\bcommand\b/gi, to: "memerintah" },
    { from: /\border\b/gi, to: "memerintahkan" },
    { from: /\bdirect\b/gi, to: "mengarahkan" },
    { from: /\binstruct\b/gi, to: "menginstruksikan" },
    { from: /\bteach\b/gi, to: "mengajar" },
    { from: /\beducate\b/gi, to: "mendidik" },
    { from: /\btrain\b/gi, to: "melatih" },
    { from: /\bcoach\b/gi, to: "melatih" },
    { from: /\bmentor\b/gi, to: "membimbing" },
    { from: /\btutor\b/gi, to: "mengajar" },
    { from: /\bguide\b/gi, to: "membimbing" },
    { from: /\blead\b/gi, to: "memimpin" },
    { from: /\bshow\b/gi, to: "menunjukkan" },
    { from: /\bdemonstrate\b/gi, to: "mendemonstrasikan" },
    { from: /\billustrate\b/gi, to: "mengilustrasikan" },
    { from: /\bexemplify\b/gi, to: "memberi contoh" },
    { from: /\bmodel\b/gi, to: "memodelkan" },
    { from: /\bsimulate\b/gi, to: "mensimulasikan" },
    { from: /\bmimic\b/gi, to: "meniru" },
    { from: /\bcopy\b/gi, to: "menyalin" },
    { from: /\bduplicate\b/gi, to: "menduplikasi" },
    { from: /\breproduce\b/gi, to: "mereproduksi" },
    { from: /\breplicate\b/gi, to: "mereplikasi" },
    { from: /\bclone\b/gi, to: "mengkloning" },
    { from: /\bmirror\b/gi, to: "mencerminkan" },
    { from: /\breflect\b/gi, to: "mencerminkan" },
    { from: /\becho\b/gi, to: "menggemakan" },
    { from: /\brepeat\b/gi, to: "mengulang" },
    { from: /\biterate\b/gi, to: "mengulang" },
    { from: /\bcycle\b/gi, to: "berputar" },
    { from: /\brotate\b/gi, to: "berputar" },
    { from: /\bspin\b/gi, to: "berputar" },
    { from: /\bturn\b/gi, to: "berputar" },
    { from: /\brevolve\b/gi, to: "berputar" },
    { from: /\borbit\b/gi, to: "mengorbit" },
    { from: /\bcircle\b/gi, to: "mengelilingi" },
    { from: /\bsurround\b/gi, to: "mengelilingi" },
    { from: /\bencircle\b/gi, to: "mengelilingi" },
    { from: /\bencompass\b/gi, to: "mencakup" },
    { from: /\binclude\b/gi, to: "mencakup" },
    { from: /\bcontain\b/gi, to: "mengandung" },
    { from: /\bcomprise\b/gi, to: "terdiri dari" },
    { from: /\bconsist\b/gi, to: "terdiri dari" },
    { from: /\bcompose\b/gi, to: "menyusun" },
    { from: /\bconstitute\b/gi, to: "membentuk" },
    { from: /\bform\b/gi, to: "membentuk" },
    { from: /\bshape\b/gi, to: "membentuk" },
    { from: /\bmold\b/gi, to: "membentuk" },
    { from: /\bforge\b/gi, to: "membentuk" },
    { from: /\bfashion\b/gi, to: "membentuk" },
    { from: /\bcraft\b/gi, to: "membuat" },
    { from: /\bbuild\b/gi, to: "membangun" },
    { from: /\bconstruct\b/gi, to: "membangun" },
    { from: /\berect\b/gi, to: "membangun" },
    { from: /\bassemble\b/gi, to: "merakit" },
    { from: /\bmanufacture\b/gi, to: "memproduksi" },
    { from: /\bproduce\b/gi, to: "menghasilkan" },
    { from: /\bgenerate\b/gi, to: "menghasilkan" },
    { from: /\bcreate\b/gi, to: "membuat" },
    { from: /\bmake\b/gi, to: "membuat" },
    { from: /\bfabricate\b/gi, to: "membuat" },
  ];

  replacements.forEach(({ from, to }) => {
    result = result.replace(from, to);
  });

  // Kapitalisasi huruf pertama
  result = result.charAt(0).toUpperCase() + result.slice(1);

  // Pastikan diakhiri titik
  if (!result.endsWith(".") && !result.endsWith("!") && !result.endsWith("?")) {
    result += ".";
  }

  return result;
}

/**
 * Format teks untuk PDF (lebih sederhana).
 */
export function generateLaporanPDF(kegiatanList, profil, periode) {
  const lines = [];

  // Header
  lines.push("LAPORAN KEGIATAN PKL");
  lines.push("");
  lines.push(`Nama: ${profil?.nama || "-"}`);
  lines.push(`Kelas: ${profil?.kelas || "-"}`);
  lines.push(`Jurusan: ${profil?.jurusan || "-"}`);
  lines.push(`Sekolah: ${profil?.sekolah || "-"}`);
  lines.push(`Tempat PKL: ${profil?.tempat_pkl || "-"}`);
  lines.push(`Periode: ${periode}`);
  lines.push("");
  lines.push("=".repeat(50));
  lines.push("");

  // Group by tanggal
  const grouped = {};
  kegiatanList.forEach((k) => {
    if (!grouped[k.tanggal]) grouped[k.tanggal] = [];
    grouped[k.tanggal].push(k);
  });

  const sortedDates = Object.keys(grouped).sort();

  sortedDates.forEach((tanggal) => {
    const items = grouped[tanggal];
    lines.push(`Tanggal: ${formatDateLong(tanggal)}`);
    lines.push("");

    items.forEach((k, idx) => {
      const kegiatanFormal = formatKegiatanFormal(k.kegiatan);
      lines.push(`${idx + 1}. ${kegiatanFormal}`);

      if (k.jam_mulai) {
        lines.push(
          `   Waktu: ${k.jam_mulai} ${k.jam_selesai ? `- ${k.jam_selesai}` : ""}`,
        );
      }
      if (k.tempat) {
        lines.push(`   Tempat: ${k.tempat}`);
      }
      if (k.software) {
        lines.push(`   Software/Peralatan: ${k.software}`);
      }
      if (k.pembelajaran) {
        lines.push(`   Pembelajaran: ${formatKegiatanFormal(k.pembelajaran)}`);
      }
      if (k.kendala) {
        lines.push(`   Kendala: ${formatKegiatanFormal(k.kendala)}`);
      }
      if (k.solusi) {
        lines.push(`   Solusi: ${formatKegiatanFormal(k.solusi)}`);
      }
      lines.push("");
    });

    lines.push("-".repeat(50));
    lines.push("");
  });

  return lines.join("\n");
}
